name: SolarSpaceTechActionstToDeploy

on: push

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to Server
              uses: hengkx/ssh-deploy@v1.0.1
              env:
                USERNAME: ${{ secrets.DEPLOY_USER }}
                PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
                HOST: ${{ secrets.DEPLOY_HOST }}
                SOURCE: 'dist'
                TARGET: ${{ secrets.DEPLOY_DEST_PATH }}
                AFTER_COMMAND: 'bash run.sh'
