name: Go

on:
  push:
    tag: 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # 部署到服务器
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          ppid=`pidof GG-server`
          kill -9 $ppid
          cd /root/go/src/Solar-Space-Server
          git pull
          go build
          nohup /root/go/src/Solar-Space-Server/GG-server $
          
